CREATE TABLE IF NOT EXISTS user_profiles (
    id SMALLSERIAL PRIMARY KEY NOT NULL,
    ulid VARCHAR UNIQUE DEFAULT generate_ulid() NOT NULL,
    user_id SMALLSERIAL REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    birthday DATE NOT NULL,
    gender VARCHAR NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
)
