[build]
  # Only deploy if changes are made to the website, resume, or component library 
  ignore = "git diff --quiet $COMMIT_REF $CACHED_COMMIT_REF -- apps/www packages/react-resume packages/react-components packages/react-primitives packages/web"

  publish = "apps/www/dist"
  command = "npm run @www:deploy"
