/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as AppImport } from './routes/app'
import { Route as IndexImport } from './routes/index'
import { Route as AppIndexImport } from './routes/app/index'
import { Route as AppWorkoutsIndexImport } from './routes/app/workouts/index'
import { Route as AppMenuIndexImport } from './routes/app/menu/index'
import { Route as AppGoalsIndexImport } from './routes/app/goals/index'
import { Route as AppExercisesIndexImport } from './routes/app/exercises/index'
import { Route as AppExercisesIdImport } from './routes/app/exercises/$id'
import { Route as AppExercisesMuscleGroupsIndexImport } from './routes/app/exercises/muscle-groups/index'
import { Route as AppExercisesMuscleGroupsIdImport } from './routes/app/exercises/muscle-groups/$id'

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  path: '/',
  getParentRoute: () => AppRoute,
} as any)

const AppWorkoutsIndexRoute = AppWorkoutsIndexImport.update({
  path: '/workouts/',
  getParentRoute: () => AppRoute,
} as any)

const AppMenuIndexRoute = AppMenuIndexImport.update({
  path: '/menu/',
  getParentRoute: () => AppRoute,
} as any)

const AppGoalsIndexRoute = AppGoalsIndexImport.update({
  path: '/goals/',
  getParentRoute: () => AppRoute,
} as any)

const AppExercisesIndexRoute = AppExercisesIndexImport.update({
  path: '/exercises/',
  getParentRoute: () => AppRoute,
} as any)

const AppExercisesIdRoute = AppExercisesIdImport.update({
  path: '/exercises/$id',
  getParentRoute: () => AppRoute,
} as any)

const AppExercisesMuscleGroupsIndexRoute =
  AppExercisesMuscleGroupsIndexImport.update({
    path: '/exercises/muscle-groups/',
    getParentRoute: () => AppRoute,
  } as any)

const AppExercisesMuscleGroupsIdRoute = AppExercisesMuscleGroupsIdImport.update(
  {
    path: '/exercises/muscle-groups/$id',
    getParentRoute: () => AppRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppImport
    }
    '/app/exercises/$id': {
      id: '/app/exercises/$id'
      path: '/exercises/$id'
      fullPath: '/app/exercises/$id'
      preLoaderRoute: typeof AppExercisesIdImport
      parentRoute: typeof AppImport
    }
    '/app/exercises/': {
      id: '/app/exercises/'
      path: '/exercises'
      fullPath: '/app/exercises'
      preLoaderRoute: typeof AppExercisesIndexImport
      parentRoute: typeof AppImport
    }
    '/app/goals/': {
      id: '/app/goals/'
      path: '/goals'
      fullPath: '/app/goals'
      preLoaderRoute: typeof AppGoalsIndexImport
      parentRoute: typeof AppImport
    }
    '/app/menu/': {
      id: '/app/menu/'
      path: '/menu'
      fullPath: '/app/menu'
      preLoaderRoute: typeof AppMenuIndexImport
      parentRoute: typeof AppImport
    }
    '/app/workouts/': {
      id: '/app/workouts/'
      path: '/workouts'
      fullPath: '/app/workouts'
      preLoaderRoute: typeof AppWorkoutsIndexImport
      parentRoute: typeof AppImport
    }
    '/app/exercises/muscle-groups/$id': {
      id: '/app/exercises/muscle-groups/$id'
      path: '/exercises/muscle-groups/$id'
      fullPath: '/app/exercises/muscle-groups/$id'
      preLoaderRoute: typeof AppExercisesMuscleGroupsIdImport
      parentRoute: typeof AppImport
    }
    '/app/exercises/muscle-groups/': {
      id: '/app/exercises/muscle-groups/'
      path: '/exercises/muscle-groups'
      fullPath: '/app/exercises/muscle-groups'
      preLoaderRoute: typeof AppExercisesMuscleGroupsIndexImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AppRoute: AppRoute.addChildren({
    AppIndexRoute,
    AppExercisesIdRoute,
    AppExercisesIndexRoute,
    AppGoalsIndexRoute,
    AppMenuIndexRoute,
    AppWorkoutsIndexRoute,
    AppExercisesMuscleGroupsIdRoute,
    AppExercisesMuscleGroupsIndexRoute,
  }),
  LoginRoute,
  RegisterRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/app",
        "/login",
        "/register"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/app": {
      "filePath": "app.tsx",
      "children": [
        "/app/",
        "/app/exercises/$id",
        "/app/exercises/",
        "/app/goals/",
        "/app/menu/",
        "/app/workouts/",
        "/app/exercises/muscle-groups/$id",
        "/app/exercises/muscle-groups/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/app/": {
      "filePath": "app/index.tsx",
      "parent": "/app"
    },
    "/app/exercises/$id": {
      "filePath": "app/exercises/$id.tsx",
      "parent": "/app"
    },
    "/app/exercises/": {
      "filePath": "app/exercises/index.tsx",
      "parent": "/app"
    },
    "/app/goals/": {
      "filePath": "app/goals/index.tsx",
      "parent": "/app"
    },
    "/app/menu/": {
      "filePath": "app/menu/index.tsx",
      "parent": "/app"
    },
    "/app/workouts/": {
      "filePath": "app/workouts/index.tsx",
      "parent": "/app"
    },
    "/app/exercises/muscle-groups/$id": {
      "filePath": "app/exercises/muscle-groups/$id.tsx",
      "parent": "/app"
    },
    "/app/exercises/muscle-groups/": {
      "filePath": "app/exercises/muscle-groups/index.tsx",
      "parent": "/app"
    }
  }
}
ROUTE_MANIFEST_END */
