/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as AppImport } from './routes/app'
import { Route as IndexImport } from './routes/index'
import { Route as AppIndexImport } from './routes/app/index'
import { Route as AppWorkoutsIndexImport } from './routes/app/workouts/index'
import { Route as AppMenuIndexImport } from './routes/app/menu/index'
import { Route as AppGoalsIndexImport } from './routes/app/goals/index'
import { Route as AppExercisesIndexImport } from './routes/app/exercises/index'
import { Route as AppExercisesIdImport } from './routes/app/exercises/$id'
import { Route as AppExercisesMuscleGroupsIndexImport } from './routes/app/exercises/muscle-groups/index'
import { Route as AppExercisesMuscleGroupsIdImport } from './routes/app/exercises/muscle-groups/$id'

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  path: '/',
  getParentRoute: () => AppRoute,
} as any)

const AppWorkoutsIndexRoute = AppWorkoutsIndexImport.update({
  path: '/workouts/',
  getParentRoute: () => AppRoute,
} as any)

const AppMenuIndexRoute = AppMenuIndexImport.update({
  path: '/menu/',
  getParentRoute: () => AppRoute,
} as any)

const AppGoalsIndexRoute = AppGoalsIndexImport.update({
  path: '/goals/',
  getParentRoute: () => AppRoute,
} as any)

const AppExercisesIndexRoute = AppExercisesIndexImport.update({
  path: '/exercises/',
  getParentRoute: () => AppRoute,
} as any)

const AppExercisesIdRoute = AppExercisesIdImport.update({
  path: '/exercises/$id',
  getParentRoute: () => AppRoute,
} as any)

const AppExercisesMuscleGroupsIndexRoute =
  AppExercisesMuscleGroupsIndexImport.update({
    path: '/exercises/muscle-groups/',
    getParentRoute: () => AppRoute,
  } as any)

const AppExercisesMuscleGroupsIdRoute = AppExercisesMuscleGroupsIdImport.update(
  {
    path: '/exercises/muscle-groups/$id',
    getParentRoute: () => AppRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/app/': {
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppImport
    }
    '/app/exercises/$id': {
      preLoaderRoute: typeof AppExercisesIdImport
      parentRoute: typeof AppImport
    }
    '/app/exercises/': {
      preLoaderRoute: typeof AppExercisesIndexImport
      parentRoute: typeof AppImport
    }
    '/app/goals/': {
      preLoaderRoute: typeof AppGoalsIndexImport
      parentRoute: typeof AppImport
    }
    '/app/menu/': {
      preLoaderRoute: typeof AppMenuIndexImport
      parentRoute: typeof AppImport
    }
    '/app/workouts/': {
      preLoaderRoute: typeof AppWorkoutsIndexImport
      parentRoute: typeof AppImport
    }
    '/app/exercises/muscle-groups/$id': {
      preLoaderRoute: typeof AppExercisesMuscleGroupsIdImport
      parentRoute: typeof AppImport
    }
    '/app/exercises/muscle-groups/': {
      preLoaderRoute: typeof AppExercisesMuscleGroupsIndexImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AppRoute.addChildren([
    AppIndexRoute,
    AppExercisesIdRoute,
    AppExercisesIndexRoute,
    AppGoalsIndexRoute,
    AppMenuIndexRoute,
    AppWorkoutsIndexRoute,
    AppExercisesMuscleGroupsIdRoute,
    AppExercisesMuscleGroupsIndexRoute,
  ]),
  LoginRoute,
  RegisterRoute,
])

/* prettier-ignore-end */
