name: CI Code Quality Check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  code_check:
    name: Formatting, Linting, and Type Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js v18
        uses: actions/setup-node@v3

      - name: Install Dependencies
        run: npm ci

      - name: Build React Resume
        run: npm run @react-resume run build

      - name: Build Jupiter Web Library
        run: npm run @web run build
    
      - name: Build React Primtive Components Library
        run: npm run @react-primitives run build

      - name: Build React Component Library
        run: npm run @react-components run build

      - name: Check Types and Code Style
        run: npm run check
